<?php

declare(strict_types=1);

namespace Modules\{{Studly}}\Http\Controllers;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Log;
use Modules\{{Studly}}\Models\{{Entity}};
use Spine\Services\ActivityLogService;

/**
 * CRUD {{Entity}} — generated by module:make-spine.
 *
 * Activity log OTOMATIS via EntityCreated/Updated/Deleted (HasLifecycleHooks)
 * -> listener Log{{Entity}}Activity di ServiceProvider.
 */
class {{Entity}}Controller extends Controller
{
    public function __construct(private readonly ActivityLogService $activityLog)
    {
    }

    public function index(): JsonResponse
    {
        // Kontrak API Spine: bungkus {data: [...]} — konsisten dengan core.
        return response()->json(['data' => {{Entity}}::orderByDesc('id')->get()]);
    }

    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'name'        => ['required', 'string', 'max:190'],
            'description' => ['nullable', 'string'],
            'status'      => ['sometimes', 'string', 'in:' . implode(',', {{Entity}}::STATUSES)],
        ]);

        $entity = {{Entity}}::create($validated);

        Log::info("[{{Entity}}] created", ['id' => $entity->id, 'name' => $entity->name]);

        return response()->json($entity, 201);
    }

    public function show(int $id): JsonResponse
    {
        $entity = {{Entity}}::find($id);

        if (! $entity) {
            return response()->json(['message' => '{{Entity}} not found'], 404);
        }

        return response()->json($entity);
    }

    public function update(int $id, Request $request): JsonResponse
    {
        $entity = {{Entity}}::find($id);

        if (! $entity) {
            return response()->json(['message' => '{{Entity}} not found'], 404);
        }

        $validated = $request->validate([
            'name'        => ['sometimes', 'string', 'max:190'],
            'description' => ['nullable', 'string'],
            'status'      => ['sometimes', 'string', 'in:' . implode(',', {{Entity}}::STATUSES)],
        ]);

        $entity->update($validated);

        Log::info("[{{Entity}}] updated", ['id' => $entity->id, 'name' => $entity->name]);

        return response()->json($entity);
    }

    public function destroy(int $id): JsonResponse
    {
        $entity = {{Entity}}::find($id);

        if (! $entity) {
            return response()->json(['message' => '{{Entity}} not found'], 404);
        }

        $entity->delete();

        return response()->json(['message' => '{{Entity}} deleted']);
    }

    public function activityLogs(int $id): JsonResponse
    {
        if (! {{Entity}}::find($id)) {
            return response()->json(['message' => '{{Entity}} not found'], 404);
        }

        $logs = $this->activityLog
            ->query()
            ->where('subject_type', {{Entity}}::class)
            ->where('subject_id', $id)
            ->orderByDesc('created_at')
            ->get()
            ->map(fn ($log) => [
                'id'          => $log->id,
                'description' => $log->description,
                'causer'      => $log->causer?->name ?? 'System',
                'properties'  => $log->properties,
                'at'          => $log->created_at?->toIso8601String(),
            ]);

        return response()->json(['data' => $logs]);
    }
}
