<?php

declare(strict_types=1);

/**
 * MANIFEST MODUL — kontrak frontend (generated by module:make-spine).
 *
 * 'menu' → Sidebar (padanan add_sidebar_menu_item)
 * 'widgets' → Dashboard per area
 * 'detail_tabs' → panel detail per record (api placeholder {id})
 *
 * @return array{menu: list<array{slug: string, label: string, icon: string, href: string, position: int}>, widgets: list<array{id: string, area: string, title: string, api: string}>, detail_tabs: list<array{slug: string, label: string, icon: string, api: string, position: int}>}
 */
return [
    'menu' => [
        [
            'slug'     => '{{route}}',
            'label'    => '{{label}}',
            'icon'     => '📦',
            'href'     => '/{{route}}',
            'position' => 90,
        ],
    ],

    'widgets' => [
        [
            'id'    => '{{route}}-items',
            'area'  => 'right-4',
            'title' => '{{label}}',
            'api'   => '/api/v1/{{route}}',
        ],
    ],

    'detail_tabs' => [
        [
            'slug'     => 'overview',
            'label'    => 'Overview',
            'icon'     => '👁️',
            'api'      => '/api/v1/{{route}}/{id}',
            'position' => 10,
        ],
        [
            'slug'     => 'activity',
            'label'    => 'Activity',
            'icon'     => '🕐',
            'api'      => '/api/v1/{{route}}/{id}/activity-logs',
            'position' => 20,
        ],
    ],
];
