<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Tabel {{table}} — generated by module:make-spine.
 * Konvensi: bigIncrements + ulid (HasUlids) + status (draft/in_progress/done).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('{{table}}', function (Blueprint $table) {
            $table->bigIncrements('id'); // BIGINT unsigned — alias eksplisit dari $table->id()
            $table->string('ulid', 26)->nullable()->unique(); // HasUlids
            $table->string('name');
            $table->text('description')->nullable();
            $table->string('status', 32)->default('draft'); // draft|in_progress|done
{{parent_fk}}
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('{{table}}');
    }
};
