<?php

declare(strict_types=1);

namespace Modules\{{Studly}}\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Model;
use Spine\Traits\HasLifecycleHooks;

/**
 * {{Entity}} — entity modul {{Studly}} (generated by module:make-spine).
 *
 * Konvensi Spine:
 *   - HasLifecycleHooks: otomatis dispatch EntityCreated/Updated/Deleted
 *   - HasUlids: identitas publik (kolom 'ulid', bukan uuid)
 *   - konstanta status: source of truth untuk UI "Mark as" + hook parent
 */
class {{Entity}} extends Model
{
    use HasLifecycleHooks;
    use HasUlids;

    public const STATUS_DRAFT = 'draft';
    public const STATUS_IN_PROGRESS = 'in_progress';
    public const STATUS_DONE = 'done';

    public const STATUSES = [
        self::STATUS_DRAFT,
        self::STATUS_IN_PROGRESS,
        self::STATUS_DONE,
    ];

    protected $fillable = ['name', 'description', 'status', 'ulid'];

    protected $casts = [
        'id' => 'integer',
    ];

    /**
     * HasUlids default mengisi PRIMARY KEY — override agar mengisi kolom 'ulid'.
     */
    public function uniqueIds(): array
    {
        return ['ulid'];
    }
}
